# Workflow syntax:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: cpp-linter

on:
  push:
    paths-ignore: "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install llvm
        run: sudo apt install llvm-11-dev
      - name: Install clang
        run: sudo apt install clang-11 --install-suggests
      - name: Install cmake
        run: sudo apt install cmake
      - name: List environment
        run: echo $USER; ls -la /; sudo ls -la /usr/bin
      - name: Build Chipstar
        run: pwd; ls -la ./; mkdir build && cd build; sudo cmake ../
      - name: C/C++ Linter
        uses: cpp-linter/cpp-linter-action@v2.9.0
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          version: 11
          files-changed-only: false
          lines-changed-only: false
          extensions: 'cc,hh'
          tidy-checks: '-*,readability-*,modernize-*,clang-analyzer-*'
          ignore: '.github|src/CHIPBindingsInternal.hh|src/common.hh|src/CHIPException.hh|src/backend/OpenCL/CHIPBackendOpenCL.hh|src/hipCtx.hh|src/hip_conversions.hh|src/SPIRVFuncInfo.hh|src/Filesystem.hh|src/logging.hh|spirv-extractor/spirv-extractor.cc|llvm_passes/SPIRVImageType.cc|src/spirv_hiprtc.cc|samples|include/hip/devicelib/atomics.hh|include/hip/spirv_hip.hh|tests|include'
      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1

